name: Bug Report
description: Create a report to help us improve
title: "[Bug]: "
labels: [type-bug, triage]
body:
  - type: markdown
    attributes:
      value: |
         Thanks for taking an intrest in Conda! 🐍

        Going through bugs and issues takes up a lot of time, so be kind to your fellow developer by taking the time to fill out all the areas to the best of your ability.
        
        There will always be more items than there is time to do them, and so we will need to selectly close bugs that don't have enough info, so we can focus our time on helping people like you who follow the process! By asking questions in a structured way (following this) it will be much easier to help you.
        
       There are also already a lot of open issues, so please take 2 minutes and search through existing ones to see if what you are experiencing already exists

       Thanks for helping Conda be amazing. We are nothing without the community 🍻

   - type: checkboxes
    id: checks
    attributes:
      label: Checklist
      description: Please confirm and check all the following options.
      options:
        - label: I added a very descriptive title
          required: true
        - label: I searched for other issues and couldn't find a solution or duplicate
          required: true
        - label: I already searched in Google and didn't find any information or help
          required: true
        - label: I looked at the [docs](https://docs.conda.io/projects/conda/en/latest/user-guide/index.html) and didn't see anything to help
          required: true

  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen? This really helps us triage quicker and greatly increases the chance that we can get around to correcting
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: input
    id: fastapi-version
    attributes:
      label: FastAPI Version
      description: |
        What FastAPI version are you using?

        You can find the FastAPI version with:

        ```bash
        python -c "import fastapi; print(fastapi.__version__)"
        ```
    validations:
      required: true
  - type: textarea
    id: info
    attributes:
      label: Conda info
      description: |
        Lets get the rundown of you conda setup. Run the following from your command lone and paste the output

        ```bash
        conda info
        ```
      render: shell
  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any additional context information or screenshots you think are useful.
