name: Question
description: For questions about pyscript
body:
  - type: markdown
    attributes:
      value: |
        Do you have a question or discussion you would like to start regarding PyScript? Click on the following link to see the best place for it: [Community forms](https://community.anaconda.cloud/c/tech-topics/pyscript)

        If you have a general question about Python you can 

        Thanks for helping PyScript be amazing. We are nothing without people like you helping build a better community 💐!
